project:
  type: website

website:
  title: <img src="/images/logo.png" width="50px">
  description: "neuroscience lab"
  favicon: images/logo.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people/index.qmd
        text: People
      - href: research/index.qmd
        text: Research
      - href: research/publications.qmd
        text: Publications
      - href: code_and_data.qmd
        text: Code & data
      
      
  body-footer: |
    <center><img src="/images/HHMI_Janelia_Logo-Black.png" width="120px" alt="Janelia"></img><br>
    <font size="2pt">  Powered by [Quarto](https://www.quarto.org). &copy; Marius Pachitariu & Carsen Stringer lab, 2023.</font></center>

format:
  html:
    theme: litera
    toc: true
    css: styles.css
    grid:
      margin-width: 200px
      body-width: 900px

execute:
  freeze: auto

