project:
  type: website

website:
  title: <img src="/images/logoBDI.png" width="50px"> Biological Dynamics & Instrumentation Group
  description: "Biological Dynamics & Instrumentation Group"
  favicon: images/logoBDI2.png

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people/index.qmd
        text: Team
      - href: research/index.qmd
        text: Research
      - href: research/publications.qmd
        text: Publications
      - href: code_and_data.qmd
        text: Code & data
      
      
  body-footer: |
    <center><img src="/images/HHMI_Janelia_Logo-Black.png" width="120px" alt="Janelia"></img><br>
    <font size="2pt">  Powered by [Quarto](https://www.quarto.org). &copy; Wong-Campos lab, 2025.</font></center>

format:
  html:
    include-in-header: 
      text: |
        <script>
        document.addEventListener('DOMContentLoaded', function() {
          const isHomePage = window.location.pathname === '/' || 
                              window.location.pathname.endsWith('index.html') ||
                              window.location.pathname.endsWith('/');
          
          if (isHomePage) {
            const topImage = document.createElement('div');
            topImage.className = 'top-image';
            topImage.innerHTML = '<img src="images/logo.png" alt="Banner">';
            
            const navbar = document.querySelector('.navbar');
            if (navbar && navbar.parentNode) {
              navbar.parentNode.insertBefore(topImage, navbar);
            }
          }
        });
        </script>
    theme: sandstone
    toc: true
    css: styles.css
    grid:
      margin-width: 200px
      body-width: 900px

execute:
  freeze: auto

